// GET ALL SEARCH
export const GET_ALL_SEARCH_REQUESTED = 'GET_ALL_SEARCH_REQUESTED';
export const GET_ALL_SEARCH_SUCCESS = 'GET_ALL_SEARCH_SUCCESS';
export const GET_ALL_SEARCH_FAILED = 'GET_ALL_SEARCH_FAILED';