// GET ALL DASHBAORD
export const GET_DASHBOARD_DETAILS_REQUESTED = "GET_DASHBOARD_DETAILS_REQUESTED";
export const GET_DASHBOARD_DETAILS_SUCCESS = "GET_DASHBOARD_DETAILS_SUCCESS";
export const GET_DASHBOARD_DETAILS_FAILED = "GET_DASHBOARD_DETAILS_FAILED";
