// GET ALL REALISE NOTES
export const GET_ALL_REALISE_NOTE_REQUESTED = "GET_ALL_REALISE_NOTE_REQUESTED";
export const GET_ALL_REALISE_NOTE_SUCCESS = "GET_ALL_REALISE_NOTE_SUCCESS";
export const GET_ALL_REALISE_NOTE_FAILED = "GET_ALL_REALISE_NOTE_FAILED";

// ADD A REALISE NOTE
export const ADD_REALISE_NOTE_REQUESTED = "ADD_REALISE_NOTE_REQUESTED";
export const ADD_REALISE_NOTE_SUCCESS = "ADD_REALISE_NOTE_SUCCESS";
export const ADD_REALISE_NOTE_FAILED = "ADD_REALISE_NOTE_FAILED";

// GET A REALISE NOTE DETAILS
export const GET_REALISE_NOTE_DETAILS_REQUESTED =
  "GET_REALISE_NOTE_DETAILS_REQUESTED";
export const GET_REALISE_NOTE_DETAILS_SUCCESS =
  "GET_REALISE_NOTE_DETAILS_SUCCESS";
export const GET_REALISE_NOTE_DETAILS_FAILED =
  "GET_REALISE_NOTE_DETAILS_FAILED";

// UPDATE A REALISE NOTE
export const UPDATE_REALISE_NOTE_REQUESTED = "UPDATE_REALISE_NOTE_REQUESTED";
export const UPDATE_REALISE_NOTE_SUCCESS = "UPDATE_REALISE_NOTE_SUCCESS";
export const UPDATE_REALISE_NOTE_FAILED = "UPDATE_REALISE_NOTE_FAILED";

// DELETE A REALISE NOTE
export const DELETE_REALISE_NOTE_REQUESTED = "DELETE_REALISE_NOTE_REQUESTED";
export const DELETE_REALISE_NOTE_SUCCESS = "DELETE_REALISE_NOTE_SUCCESS";
export const DELETE_REALISE_NOTE_FAILED = "DELETE_REALISE_NOTE_FAILED";

// SET REALISE NOTES MODAL
export const SET_REALISE_NOTE_MODAL_REQUESTED =
  "SET_REALISE_NOTE_MODAL_REQUESTED";

// RESET THE ERRORS - MESSAGES
export const RESET_REALISE_NOTE_ERRORS_REQUESTED =
  "RESET_REALISE_NOTE_ERRORS_REQUESTED";

// CHANGE SEARCH
export const CHANGE_REALISE_NOTE_SEARCH_REQUESTED =
  "CHANGE_REALISE_NOTE_SEARCH_REQUESTED";
