// GET ALL SLAVE MACHINES
export const GET_ALL_SLAVE_MACHINES_REQUESTED =
  "GET_ALL_SLAVE_MACHINES_REQUESTED";
export const GET_ALL_SLAVE_MACHINES_SUCCESS = "GET_ALL_SLAVE_MACHINES_SUCCESS";
export const GET_ALL_SLAVE_MACHINES_FAILED = "GET_ALL_SLAVE_MACHINES_FAILED";

// ADD A SLAVE MACHINE
export const ADD_SLAVE_MACHINE_REQUESTED = "ADD_SLAVE_MACHINE_REQUESTED";
export const ADD_SLAVE_MACHINE_SUCCESS = "ADD_SLAVE_MACHINE_SUCCESS";
export const ADD_SLAVE_MACHINE_FAILED = "ADD_SLAVE_MACHINE_FAILED";

// GET A SLAVE MACHINE DETAILS
export const GET_SLAVE_MACHINE_DETAILS_REQUESTED =
  "GET_SLAVE_MACHINE_DETAILS_REQUESTED";
export const GET_SLAVE_MACHINE_DETAILS_SUCCESS =
  "GET_SLAVE_MACHINE_DETAILS_SUCCESS";
export const GET_SLAVE_MACHINE_DETAILS_FAILED =
  "GET_SLAVE_MACHINE_DETAILS_FAILED";

// UPDATE A SLAVE MACHINE
export const UPDATE_SLAVE_MACHINE_REQUESTED = "UPDATE_SLAVE_MACHINE_REQUESTED";
export const UPDATE_SLAVE_MACHINE_SUCCESS = "UPDATE_SLAVE_MACHINE_SUCCESS";
export const UPDATE_SLAVE_MACHINE_FAILED = "UPDATE_SLAVE_MACHINE_FAILED";

// DELETE A SLAVE MACHINE
export const DELETE_SLAVE_MACHINE_REQUESTED = "DELETE_SLAVE_MACHINE_REQUESTED";
export const DELETE_SLAVE_MACHINE_SUCCESS = "DELETE_SLAVE_MACHINE_SUCCESS";
export const DELETE_SLAVE_MACHINE_FAILED = "DELETE_SLAVE_MACHINE_FAILED";

// SET SLAVE MACHINES MODAL
export const SET_SLAVE_MACHINE_MODAL_REQUESTED =
  "SET_SLAVE_MACHINE_MODAL_REQUESTED";

// RESET THE ERRORS - MESSAGES
export const RESET_SLAVE_MACHINE_ERRORS_REQUESTED =
  "RESET_SLAVE_MACHINE_ERRORS_REQUESTED";

// CHANGE SEARCH
export const CHANGE_SLAVE_MACHINES_SEARCH_REQUESTED =
  "CHANGE_SLAVE_MACHINES_SEARCH_REQUESTED";
