// GET ALL PART FIELDS
export const GET_ALL_PART_FIELDS_REQUESTED =
  "GET_ALL_PART_FIELDS_REQUESTED";
export const GET_ALL_PART_FIELDS_SUCCESS = "GET_ALL_PART_FIELDS_SUCCESS";
export const GET_ALL_PART_FIELDS_FAILED = "GET_ALL_PART_FIELDS_FAILED";

// ADD A PART FIELDS
export const ADD_PART_FIELDS_REQUESTED = "ADD_PART_FIELDS_REQUESTED";
export const ADD_PART_FIELDS_SUCCESS = "ADD_PART_FIELDS_SUCCESS";
export const ADD_PART_FIELDS_FAILED = "ADD_PART_FIELDS_FAILED";

// GET A PART FIELDS DETAILS
export const GET_PART_FIELDS_DETAILS_REQUESTED =
  "GET_PART_FIELDS_DETAILS_REQUESTED";
export const GET_PART_FIELDS_DETAILS_SUCCESS =
  "GET_PART_FIELDS_DETAILS_SUCCESS";
export const GET_PART_FIELDS_DETAILS_FAILED =
  "GET_PART_FIELDS_DETAILS_FAILED";

// UPDATE A PART FIELDS
export const UPDATE_PART_FIELDS_REQUESTED = "UPDATE_PART_FIELDS_REQUESTED";
export const UPDATE_PART_FIELDS_SUCCESS = "UPDATE_PART_FIELDS_SUCCESS";
export const UPDATE_PART_FIELDS_FAILED = "UPDATE_PART_FIELDS_FAILED";

// DELETE A PART FIELDS
export const DELETE_PART_FIELDS_REQUESTED = "DELETE_PART_FIELDS_REQUESTED";
export const DELETE_PART_FIELDS_SUCCESS = "DELETE_PART_FIELDS_SUCCESS";
export const DELETE_PART_FIELDS_FAILED = "DELETE_PART_FIELDS_FAILED";

// SET PART FIELDS MODAL
export const SET_PART_FIELDS_MODAL_REQUESTED =
  "SET_PART_FIELDS_MODAL_REQUESTED";

// RESET THE ERRORS - MESSAGES
export const RESET_PART_FIELDS_ERRORS_REQUESTED =
  "RESET_PART_FIELDS_ERRORS_REQUESTED";

// CHANGE SEARCH
export const CHANGE_PART_FIELDS_SEARCH_REQUESTED =
  "CHANGE_PART_FIELDS_SEARCH_REQUESTED";
